apiVersion: v1
kind: Service
metadata:
  name: extension-knative-eventing
  labels:
    app: extension-knative-eventing
    tekton-dashboard-extension: "true"
  annotations:
    tekton-dashboard-endpoints: "/webhook"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: extension-knative-eventing